version: "3.7"
services:

  gourgeist:
    build:
      context: .
      dockerfile: ./cmd/gourgeist/Dockerfile
    container_name: gourgeist
    depends_on:
      - trevenant
      - mongo

  trevenant:
    build:
      context: .
      dockerfile: ./cmd/trevenant/Dockerfile
    container_name: trevenant
    depends_on:
      - mongo

  mongo:
    image: "mongo:5.0"
    container_name: mongo
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    restart: always
    ports:
      - "27017:27017"
