version: "3"

dotenv: [".env"]

tasks:
  mongo-dump:
    desc: "Dump the contents of MongoDB onto a local file"
    cmds:
      - mkdir -p backups
      - mongodump -u=${MONGO_USERNAME} -p=${MONGO_PASSWORD} -o "backups/dump_$(date +'%m_%d_%Y_%H:%M')"

  mongo-recover:
    desc: "Recover MongoDB from the most recent save"
    cmds:
      - mongorestore --username $MONGO_USERNAME --password $MONGO_PASSWORD $(ls -d backups/dump_* | tail -1)

  mongo-tools-setup:
    desc: "Download and install MongoDB tools"
    cmds:
      - curl https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.5.3.tgz -o mongodb-database-tools-ubuntu2004-x86_64-100.5.3.tgz
      - tar -zxvf mongodb-database-tools-*-100.5.3.tgz
      - mv mongodb-database-tools-*-100.5.3/bin/* /usr/local/bin/
      # - echo 'export PATH=$PATH:/usr/local/bin/mongodb-database-tools-ubuntu2004-x86_64-100.5.3/bin' >> ~/.bashrc
      - rm mongodb-database-tools-*-100.5.3.tgz

  mongo-check:
    internal: true
    cmds:
      - ./scripts/mongo_check.sh config.yaml

  proto:
    desc: "Generate the .pb. files"
    cmds:
      - mkdir -p gourgeist/pkg/ghastly/proto
      - mkdir -p trevenant/ghastly/proto
      - protoc
        --go_out=gourgeist/pkg/ghastly/proto --go_opt=paths=source_relative
        --go-grpc_out=gourgeist/pkg/ghastly/proto --go-grpc_opt=paths=source_relative
        ghastly.proto
      - python3 -m grpc_tools.protoc -I.
        --python_out=trevenant/ghastly/proto --grpc_python_out=trevenant/ghastly/proto
        ghastly.proto
      # Replace import with relative import.
      - sed -i 's/^import .*_pb2 as/from . \0/' trevenant/ghastly/proto/ghastly_pb2_grpc.py

  build:
    desc: "Build the docker-compose file"
    cmds:
      - docker-compose build --parallel

  start-all:
    deps: [mongo-check]
    desc: "Start all the necessary containers"
    cmds:
      - docker-compose --env-file .env up -d

  start-gourgeist-only:
    desc: "Start the Gourgeist container only"
    cmds:
      - docker-compose build gourgeist
      - docker-compose --env-file .env up gourgeist

  start-skeleton:
    cmds:
      - docker-compose --env-file .env -f docker-compose-skeleton.yaml up -d

  start-local:
    desc: "Start a local version of Gourgeist (no charts)"
    cmds:
      - go run cmd/gourgeist/main.go

  test:
    desc: "Run the local tests on covermode=set"
    cmds:
      - go test ./gourgeist/... -covermode=set
