name: Garbage Collect Old Docker Images

on:
  schedule:
    - cron: "0 9 * * *"

jobs:
  build:
    name: Garbage collect old images
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Execute doctl command
        run: |
          echo y | doctl registry garbage-collection start
